# Minima theme configuration
remote_theme: jekyll/minima
plugins:
  - jekyll-remote-theme

# valid social icon names can be found at https://fontawesome.com/search?ic=brands

minima:
  skin: auto
  social_links:
    - title: GitHub
      icon: github
      url: "https://github.com/azurepolarbear"
    - title: X (formerly Twitter)
      icon: x-twitter
      url: "https://x.com/azurepolarbear"
    - title: Instagram
      icon: instagram
      url: "https://instagram.com/azurepolarbear"

header_pages:
  - index.md
  - projects.md

title: azurepolarbear - code artist
description: algorithmic artist making beautiful things with code ğŸ’™ğŸ‘©ğŸ½â€ğŸ’»
show_downloads: false
