# Minimal Theme
remote_theme: pages-themes/minimal@v0.2.0
plugins:
- jekyll-remote-theme

title: azurepolarbear - code artist
description: (she/her) algorithmic artist making beautiful things with code ğŸ’™ğŸ‘©ğŸ½â€ğŸ’»
logo: "./assets/img/logo.png"
show_downloads: false
